// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Memories = __t.object("Memories", {
  id: __t.string(),
  text: __t.string(),
  embedding: __t.array(__t.f32()),
  importance: __t.f32(),
  category: __t.string(),
  createdAt: __t.u64(),
});
export type Memories = __Infer<typeof Memories>;

export const Messages = __t.object("Messages", {
  id: __t.string(),
  sessionId: __t.string(),
  role: __t.string(),
  content: __t.string(),
  timestamp: __t.u64(),
});
export type Messages = __Infer<typeof Messages>;

export const Sessions = __t.object("Sessions", {
  id: __t.string(),
  updatedAt: __t.u64(),
  metadataJson: __t.string(),
});
export type Sessions = __Infer<typeof Sessions>;
